### ISSUE TITLE
Safari Fails to Record with WAV Encoder

### ISSUE THREAD

**Issue by AndrejHronco** [chrisguttandin/extendable-media-recorder#642] opened 2021-04-30 19:37 UTC
Hi Chris,
Getting these errors on Safari 14.1 / 14.2 right after calling register and connect when using wav encoder:

`await register(await connect());`

```
[Error] Error: The error you provided does not contain a stack trace.
[Error] Unhandled Promise Rejection: TypeError: 'application/javascript; charset=utf-8' is not a valid JavaScript MIME type.
```

thank you

**Comment by chrisguttandin** [comment] 2021-04-30 21:24
Hi Andre, unfortunately I can't reproduce this. It works for me in Safari v14.1. Not sure about v14.2. Is that the tech preview?

**Comment by tranquocviet226** [comment] 2021-05-19 03:45
I got another error with Safari 13.1.2

![image](https://user-images.githubusercontent.com/57559641/118753455-3f7e2d80-b88f-11eb-9a76-f6ea05e7d3f8.png)

**Comment by chrisguttandin** [comment] 2021-05-20 20:58
Hi @tranquocviet226, I think the two errors are unrelated. Safari's experimental `MediaRecorder` has no `isTypeSupported()` function. I handled that in one place already but forgot to handle it everywhere. The issue should be fixed now.

https://github.com/chrisguttandin/extendable-media-recorder/commit/2161e1b3007715f7559045c32c41ee2d79ef453a

I'm going to close the issue now.  @AndrejHronco and @tranquocviet226, please feel free to re-open it if any of the two errors still persists.

**Closed by chrisguttandin** 2021-05-20 20:58 UTC
