### ISSUE TITLE
There is already an encoder stored which handles exactly the same mime types

### ISSUE THREAD

**Issue by tranquocviet226** [chrisguttandin/extendable-media-recorder#645] opened 2021-05-18 10:46 UTC
Hi, I got an error

![image](https://user-images.githubusercontent.com/57559641/118638312-e8ca1280-b800-11eb-84f4-5e162b5cf718.png)

**Comment by mylnikovD** [comment] 2021-05-18 11:51
It seems that it happens because you have multiple invocations of code that connects codecs - 
`await register(await connect());`

I'm using it with React and put it in App.jsx componentDidMount lifecycle (or useEffect hook with empty deps array) so it would happen only once when openning the page with app and it fixed the error

**Comment by chrisguttandin** [comment] 2021-05-18 16:09
Hi @tranquocviet226, I think @mylnikovD is right (thanks for chiming in). Without any sample code I would also assume that this is the problem. Please make sure that you register each encoder only once.

I'm going to close this issue. Please feel free to reopen it in case calling `register()` multiple times wasn't the issue. Preferably with some sample code that allows me to reproduce the error.

**Closed by chrisguttandin** 2021-05-18 16:09 UTC
